# Baixa a imagem oficial do PostgreSQL
FROM postgres:latest

# Define as variáveis de ambiente para a configuração do PostgreSQL
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=postgres

# docker build -t postgres_custom .
# docker run --name postgres_container -p 5432:5432 -d postgres_custom

